"""
AUTO FEATURE MANAGER
Manage features without editing code
"""

import json
import os
import importlib
import sys
from pathlib import Path
from typing import Dict, List, Any
from dataclasses import dataclass, asdict

@dataclass
class FeatureConfig:
    """Feature configuration"""
    name: str
    enabled: bool = True
    version: str = "1.0.0"
    description: str = ""
    dependencies: List[str] = None
    config: Dict[str, Any] = None
    
    def __post_init__(self):
        if self.dependencies is None:
            self.dependencies = []
        if self.config is None:
            self.config = {}
    
    def to_dict(self):
        return asdict(self)
    
    @classmethod
    def from_dict(cls, data: dict):
        return cls(**data)

class AutoFeatureManager:
    """Auto feature management system"""
    
    def __init__(self, app, config):
        self.app = app
        self.config = config
        self.features_dir = Path(__file__).parent.parent / "auto_features"
        self.registry_file = self.features_dir / "feature_registry.json"
        self.loaded_features: Dict[str, Any] = {}
        
        # Create directories
        self.features_dir.mkdir(exist_ok=True)
        
        # Initialize registry
        self._init_registry()
    
    def _init_registry(self):
        """Initialize feature registry"""
        if not self.registry_file.exists():
            self.registry = {}
            self._save_registry()
        else:
            with open(self.registry_file, 'r') as f:
                self.registry = json.load(f)
    
    def _save_registry(self):
        """Save feature registry"""
        with open(self.registry_file, 'w') as f:
            json.dump(self.registry, f, indent=2)
    
    def create_feature(self, feature_config: FeatureConfig):
        """Create a new feature"""
        # Create feature directory
        feature_dir = self.features_dir / feature_config.name
        feature_dir.mkdir(exist_ok=True)
        
        # Create feature files
        self._create_feature_files(feature_dir, feature_config)
        
        # Add to registry
        self.registry[feature_config.name] = feature_config.to_dict()
        self._save_registry()
        
        print(f"✅ Feature created: {feature_config.name}")
        return feature_dir
    
    def _create_feature_files(self, feature_dir: Path, config: FeatureConfig):
        """Create feature files"""
        # Create __init__.py
        init_content = f'''
"""
{config.name} - {config.description}
"""

from .{config.name}_main import {config.name.capitalize()}Feature

__all__ = ['{config.name.capitalize()}Feature']
'''
        
        with open(feature_dir / "__init__.py", 'w') as f:
            f.write(init_content)
        
        # Create main feature file
        main_content = f'''
"""
{config.name} Feature
Auto-generated by Nila Bot
"""

from telegram import Update
from telegram.ext import ContextTypes

class {config.name.capitalize()}Feature:
    """{config.description}"""
    
    def __init__(self, app, config):
        self.app = app
        self.config = config
        
        # Feature configuration
        self.feature_config = {config.config}
    
    def register(self):
        """Register feature handlers"""
        # Add your command handlers here
        # Example:
        # from telegram.ext import CommandHandler
        # self.app.add_handler(CommandHandler("{config.name}", self.{config.name}_command))
        pass
    
    async def {config.name}_command(self, update: Update, context: ContextTypes.DEFAULT_TYPE):
        """{config.name} command handler"""
        await update.message.reply_text("Feature {config.name} is working!")
    
    # Add more methods as needed
'''
        
        with open(feature_dir / f"{config.name}_main.py", 'w') as f:
            f.write(main_content)
        
        # Create config file
        config_file = feature_dir / "config.json"
        with open(config_file, 'w') as f:
            json.dump(config.config, f, indent=2)
        
        # Create requirements file
        if config.dependencies:
            req_file = feature_dir / "requirements.txt"
            with open(req_file, 'w') as f:
                f.write("\n".join(config.dependencies))
    
    def load_feature(self, feature_name: str) -> bool:
        """Load a feature dynamically"""
        if feature_name in self.loaded_features:
            print(f"⚠️ Feature {feature_name} is already loaded")
            return True
        
        if feature_name not in self.registry:
            print(f"❌ Feature {feature_name} not found in registry")
            return False
        
        try:
            # Import feature module
            feature_path = self.features_dir / feature_name
            if not feature_path.exists():
                print(f"❌ Feature directory not found: {feature_name}")
                return False
            
            # Add to Python path
            sys.path.insert(0, str(self.features_dir))
            
            # Import module
            module = importlib.import_module(f"{feature_name}")
            
            # Get feature class
            feature_class = getattr(module, f"{feature_name.capitalize()}Feature", None)
            
            if not feature_class:
                print(f"❌ Feature class not found: {feature_name.capitalize()}Feature")
                return False
            
            # Instantiate and register
            feature_instance = feature_class(self.app, self.config)
            feature_instance.register()
            
            # Store instance
            self.loaded_features[feature_name] = feature_instance
            
            # Update registry
            self.registry[feature_name]["loaded"] = True
            self._save_registry()
            
            print(f"✅ Feature loaded: {feature_name}")
            return True
            
        except Exception as e:
            print(f"❌ Failed to load feature {feature_name}: {e}")
            return False
    
    def unload_feature(self, feature_name: str) -> bool:
        """Unload a feature"""
        if feature_name not in self.loaded_features:
            print(f"⚠️ Feature {feature_name} is not loaded")
            return False
        
        try:
            # Get feature instance
            feature_instance = self.loaded_features[feature_name]
            
            # Call cleanup if exists
            if hasattr(feature_instance, 'cleanup'):
                feature_instance.cleanup()
            
            # Remove from loaded features
            del self.loaded_features[feature_name]
            
            # Update registry
            self.registry[feature_name]["loaded"] = False
            self._save_registry()
            
            print(f"✅ Feature unloaded: {feature_name}")
            return True
            
        except Exception as e:
            print(f"❌ Failed to unload feature {feature_name}: {e}")
            return False
    
    def enable_feature(self, feature_name: str) -> bool:
        """Enable a feature"""
        if feature_name not in self.registry:
            print(f"❌ Feature {feature_name} not found")
            return False
        
        self.registry[feature_name]["enabled"] = True
        self._save_registry()
        
        # Auto-load if not loaded
        if feature_name not in self.loaded_features:
            self.load_feature(feature_name)
        
        print(f"✅ Feature enabled: {feature_name}")
        return True
    
    def disable_feature(self, feature_name: str) -> bool:
        """Disable a feature"""
        if feature_name not in self.registry:
            print(f"❌ Feature {feature_name} not found")
            return False
        
        self.registry[feature_name]["enabled"] = False
        self._save_registry()
        
        # Auto-unload if loaded
        if feature_name in self.loaded_features:
            self.unload_feature(feature_name)
        
        print(f"✅ Feature disabled: {feature_name}")
        return True
    
    def list_features(self) -> List[Dict]:
        """List all features"""
        features = []
        
        for name, config in self.registry.items():
            features.append({
                "name": name,
                "enabled": config.get("enabled", False),
                "loaded": name in self.loaded_features,
                "description": config.get("description", ""),
                "version": config.get("version", "1.0.0")
            })
        
        return features
    
    def load_all_enabled(self):
        """Load all enabled features"""
        enabled_features = [
            name for name, config in self.registry.items()
            if config.get("enabled", False)
        ]
        
        loaded_count = 0
        for feature_name in enabled_features:
            if self.load_feature(feature_name):
                loaded_count += 1
        
        print(f"✅ Loaded {loaded_count}/{len(enabled_features)} enabled features")
        return loaded_count

# Example feature creation
def create_example_features(manager: AutoFeatureManager):
    """Create example features"""
    
    # Example: Games feature
    games_config = FeatureConfig(
        name="games",
        description="Fun games for your group",
        version="1.0.0",
        dependencies=["random", "time"],
        config={
            "enabled_games": ["trivia", "quiz", "hangman"],
            "max_players": 10,
            "score_system": True
        }
    )
    
    # Example: Music feature
    music_config = FeatureConfig(
        name="music",
        description="Music player for groups",
        version="1.0.0",
        dependencies=["youtube_dl", "pafy"],
        config={
            "max_queue_size": 20,
            "allowed_formats": ["mp3", "m4a"],
            "volume_default": 80
        }
    )
    
    # Example: Moderation feature
    moderation_config = FeatureConfig(
        name="moderation",
        description="Auto moderation tools",
        version="1.0.0",
        dependencies=[],
        config={
            "auto_warn": True,
            "max_warnings": 3,
            "ban_duration": 3600,
            "filter_words": []
        }
    )
    
    # Create features
    manager.create_feature(games_config)
    manager.create_feature(music_config)
    manager.create_feature(moderation_config)
